### ISSUE TITLE
Compiling `println!(indoc!(...))` hangs forever

### ISSUE THREAD

**Issue by brennie** [dtolnay/indoc#17]
The following never finishes compiling:

```rust
#[macro_use]
extern crate indoc;

fn main() {
    println!(indoc!("
        Help I don't compile
    "));
}
```

**Comment by dtolnay** [comment]
Thanks! This was previously reported in #12. As far as I know there is no way for this to work on the stable compiler. You can switch to the `"unstable"` feature of indoc, or use [`runtime-fmt`](https://github.com/SpaceManiac/runtime-fmt) with stable indoc, or give up on indoc.

**Comment by brennie** [comment]
Alright, thanks for the heads up. indoc is great btw :)
