### ISSUE TITLE
Add example crate that shows how to use indoc with a stable compiler

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/indoc#2]

**Comment by wimh** [comment]
Is it possible to use this crate as a "normal" crate instead of a compiler plugin? The function `unindent` would be useful when it's input is a `&str`:

    pub fn unindent(input: &str) -> String {

**Comment by dtolnay** [comment]
@wimh AFAIK a crate cannot be both a compiler plugin and a library, so I published an [`unindent` crate](https://crates.io/crates/unindent) containing the function and [added it to the readme](https://github.com/dtolnay/indoc#unindent).
