### ISSUE TITLE
Use unindent as extension function 

### ISSUE THREAD

**Issue by la10736** [dtolnay/indoc#30]
It would be great to have an extension function for `unindent()`. I'm using it in tests and use `unindent()` as postfix instead of function call improve test readability:

```rust
assert_eq!(tests, r#"
                    case_1_1_1
                    case_1_1_2
                    case_1_2_1
                    case_1_2_2
                    case_2_1_1
                    case_2_1_2
                    case_2_2_1
                    case_2_2_2"#.unindent())
```
It is better than surround string by `unindent()` function.

Just I'm not sure if is better to have two different traits for `unindent` and `unindent_bytes` or use just one for both. In the last case I need to write every single implementation (`&str`, `String`, `&[u8]`...) but in the first case I can do just two `impl` for `AsRef<str>` and `AsRef<[u8]>`.

If it is ok for you I can implement it...

**Comment by dtolnay** [comment]
Thanks, I would accept a PR for this.

**Comment by la10736** [comment]
Do you prefer just one trait or two?

**Comment by dtolnay** [comment]
I would prefer one extension trait called unindent::Unindent.
