### ISSUE TITLE
possibly os issue on windows

### ISSUE THREAD

**Issue by softprops** [dtolnay/indoc#34]
Thanks for this crate. I wish this was the default behavior for rusts multiline strings.

In any case I recently started using this in some unit tests that run across os's and found some problematic behavior on windows. This is likely do to line endings. I'm using the pretty assertions crate to see where the issue is.

My code is [here](https://github.com/softprops/sigv4/blob/23643383fdafe16364f9d6be5e8ba0624acdb429/src/main.rs#L205-L209) 

My CI logs [here](https://github.com/softprops/sigv4/runs/260182639)

And test error output here

```
Diff < left / right > :
<"HTTP/2 200 OK\n\n{\"hello\":\"aws\"}"
>"HTTP/2 200 OK\r\n\r\n                {\"hello\":\"aws\"}"
```

**Comment by dtolnay** [comment]
My understanding is that rustc is responsible for stripping \r from string literal tokens (on all platforms). I tried this program with \r\n line endings:

```rust
use indoc::indoc;

fn main() {
    println!("{:?}", indoc!(
        r#"HTTP/2 200 OK

        {"hello":"aws"}"#
    ));
}
```

and it prints out as I would expect:

```console
"HTTP/2 200 OK\n\n{\"hello\":\"aws\"}"
```

If you can reproduce rustc not stripping \r from strings in proc macro input, could you file that as a rust-lang/rust issue?

**Comment by softprops** [comment]
I ended out just going back to r#"..."# style multi-line strings for now. If I have time I'll come back and revisit.

**Comment by dtolnay** [comment]
Closing -- if someone is able to reproduce \\r not getting stripped by rustc, please report it in rust-lang/rust.
