### ISSUE TITLE
Add printing macros

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/indoc#36]
Indoc is currently not usable directly as the format string of a print macro on a stable compiler. (It's fine with the nightly-only "unstable" feature enabled.)

```console
error: format argument must be a string literal
 --> src/main.rs:4:14
  |
4 |     println!(indoc!(""));
  |              ^^^^^^^^^^
```

It would be nice to provide macros something like `printdoc!` for this common use case.

```rust
printdoc!("
    ...
    ...
    ...
");
```

**Comment by MightyPork** [comment]
This is just for curiosity - a custom trait I wrote as a work-around.

I mostly use it with format!(), so the trick consists of using `format!().unindent()`. I have added related functions for indenting. I'm not happy enough with the code yet to publish it as a crate, but it works for me.

```rust
/// Block indents and un-indents
trait RootIndent {
    /// Remove leading block indentation
    fn unindent(&self) -> String;
    /// Indent by a number of 4-space tabs
    fn indent(&self, count : usize) -> String;
    /// Indent all, except the first line, by a number of 4-space tabs
    fn indent_inner(&self, count : usize) -> String;
}

impl RootIndent for &'_ str {
    fn unindent(&self) -> String {
        if self.trim().is_empty() {
            return String::new();
        }

        let mut ll = self.lines()
            .skip_while(|l| l.trim().is_empty())
            .peekable();

        let next = ll.peek().unwrap();

        let mut space_count = next.as_bytes().iter().take_while(|c| **c == 32).count();

        ll.map(|s| {
                if s.len() > space_count {
                    &s[space_count..]
                } else {
                    ""
                }
            })
            .collect::<Vec<&str>>()
            .join("\n")
    }

    fn indent(&self, count: usize) -> String {
        let indentbare = "    ".repeat(count);
        let indentstr = "\n".to_string() + &indentbare;
        let replaced = self.replace("\n", &indentstr);
        (indentbare + &replaced).trim_end().to_string()
    }

    fn indent_inner(&self, count : usize) -> String {
        let indentbare = "    ".repeat(count);
        let indentstr = "\n".to_string() + &indentbare;
        let replaced = self.replace("\n", &indentstr);
        replaced.trim_end().to_string()
    }
}

impl RootIndent for String {
    fn unindent(&self) -> String {
        self.as_str().unindent()
    }

    fn indent(&self, count : usize) -> String {
        self.as_str().indent(count)
    }

    fn indent_inner(&self, count : usize) -> String {
        self.as_str().indent_inner(count)
    }
}

impl RootIndent for &String {
    fn unindent(&self) -> String {
        self.as_str().unindent()
    }

    fn indent(&self, count : usize) -> String {
        self.as_str().indent(count)
    }

    fn indent_inner(&self, count : usize) -> String {
        self.as_str().indent_inner(count)
    }
}

fn main() {
    // Hello, 
    //   world! 123
    //     foo
    //     bar
    //     baz
    // ...

    println!("{}", &format!(r#"
        Hello, 
          world! {}
            {inner}
        ..."#, 123, inner="foo\nbar\nbaz".indent_inner(3)
    ).unindent());
}
```

**Comment by MightyPork** [comment]
just a note if you decide to implement these macros, maybe don't use the prefix `i`, that would conflict with the [`ifmt`](https://crates.io/crates/ifmt) crate (like `iformat!()`). that's a really convenient crate, btw

**Comment by Cerberuser** [comment]
Just run into this in my own project, so I'm in, MR hopefully will be sent soon.

**Comment by Cerberuser** [comment]
A small question: how would you test if the stdout of some operation is the expected one? I'd like to add the tests for the new `printdoc!` macro, as they are here for `indoc!`, but not sure how to do this (so that they fit here). `trybuild` does not support checking the output of successful runs, AFAIK?

**Comment by MightyPork** [comment]
If `printdoc!()` is added, then something like `formatdoc!()` would also be useful. With that, you can build multi-line formatted strings with nice indentation.

Actually, now thinking of it, it'd make the most sense if `indoc!()` directly worked like this `formatdoc!()`, taking additional arguments

**Comment by Cerberuser** [comment]
Well, `formatdoc` is already added (not pushed yet), and tests for it, adapted from the `indoc` case, are already passing. Maybe that's enough, given that their implementation is exactly the same, except the macro name.
