### ISSUE TITLE
Some kind of change in behaviour in macros between 0.3 and 1.0

### ISSUE THREAD

**Issue by Nemo157** [dtolnay/indoc#39]
It sounds like it wasn't intended that the behavior changed for 1.0, but I'm getting [failures when trying to update](https://github.com/Nemo157/cbor-diag-rs/pull/82/files#file-tests-utils-mod-rs-L85). I've tried creating a small reproduction using combinations of `macro_rules!` macros invoking `indoc::indoc!` and `r#""` strings, but haven't been able to come up with anything that fails so I'm not entirely sure where the issue is :frowning:, but guessing it's something to do with macro-substitution.

**Comment by dtolnay** [comment]
Fixed in 1.0.2.
