### ISSUE TITLE
[unindent]: First line does not get unindented

### ISSUE THREAD

**Issue by matthiasbeyer** [dtolnay/indoc#45]
❤️  
  
It seems that the first line does not get unindented when using `Unindent::unindent()`. I had to do some ugly `format!("\n{}", text).unindent()` to get the appropriate result.
 
--- 

To add on that bit: I see that this is documented behaviour, but it is not expected if one sees the API. Can we improve the current situation? Either by providing an example how to get the (from my point of view) expected result or at least some big "NOTE" documentation on the function(s)?

**Comment by xpe** [comment]
@matthiasbeyer Would you please add a code example?

**Comment by dtolnay** [comment]
This behavior is appropriate for the style that the readme shows string literals being written in. I haven't heard back with an example of what you are doing, but if you are processing something other than Rust string literals from Rust source code, probably this is not the crate for you.
