### ISSUE TITLE
Support paragraphs/line breaks

### ISSUE THREAD

**Issue by qfel** [dtolnay/indoc#65]
I was looking for something to define CLI help text. In that case, you generally want arbitrarily long lines (let the terminal wrap) but for readability in source code it would be nice if they appeared wrapped.

Something like:

```rust
let text = "
    Some long paragraph.
    That is really a one line
    and the terminal will
    wrap it.
    
    Another paragraph:
      - Bullet point on a separate line
"
```

indoc! solved the indentation problem, bot not the paragraph problem: if I wrap lines in source code, they'll be wrapped in the resulting literal.

I wonder if it would make sense to add extra options to indoc! that control this behavior, eg. (a) remove new lines withing the same paragraph (so that you can wrap it in source, but will get unrolled to a single line) and (b) add a way to force a line break to disable that behavior where needed.

For (a) it could be something simple, like

```rust
indoc!{"
  Some
  paragraph.
  
  Another paragraph.
", nl=paragraph}
```

that would evaluate to "Some paragraph.\nAnother paragraph".

Not sure about (b), I suppose one could use some unusual escape sequence (eg. '\0') to mean a new line (I suspect at the macro level one cannot detect the form of a character, eg. "\n" vs a literal new line?)

Thoughts?

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate, but someone could make a different crate that addresses this use case.
