### ISSUE TITLE
Add indenting to strings

### ISSUE THREAD

**Issue by dashed** [dtolnay/indoc#7]
This crate already strips indentation. I'm wondering if it'll be useful if this crate injects indentation (the opposite behaviour).

The following may be motivation for this:

``` rust
fn main() {

    let bar = "\
multiline
string";

    let foo = format!("
        foo
        '{bar}'\
    ", bar = bar);

    println!("{}", foo);
}
/*
Output:

        foo
        'multiline
string'
*/
```

https://is.gd/zerdxG

---

I'm unsure what the usage looks like, but it may be useful to inject indentation such that `bar` variable will be properly formatted. 

Feel free to close this issue if it's out of scope or not possible.

**Comment by dtolnay** [comment]
Good idea. I will think about what the API could look like. Let me know if you come up with something yourself.

Is there something you don't like about this approach?

```rust
fn main() {
    let bar = "\
        multiline
        string";

    let foo = format!("
        foo
        '{bar}'\
    ", bar = bar);
    
    println!("{}", foo);
}
/*
Output:

        foo
        'multiline
        string'
*/
```

**Comment by dashed** [comment]
Well, for that specific example, it works 😄 .

The usecase I have is that I use a combination of `format!` and `indoc!` macros to generate sql queries from fragments of strings. Sometimes these fragments repeat (e.g. order by clauses that are identical in sub and parent queries).  

I thought it'd be nice to apply the necessary indentation to these fragments such that the overall generated sql query looks nicer (e.g. for logging).

 I don't have a hard need for this feature, but if this issue remains open and no one claims it, I may look into coming up with something when I have free time (probably as a learning experience on rust compiler plugins 😃 ).

**Comment by dtolnay** [comment]
I am closing this issue for now because I don't plan to implement this myself, but we can reopen if anyone decides they need this feature.
