### ISSUE TITLE
Make indoc work with tab-based indentation

### ISSUE THREAD

**Issue by Boscop** [dtolnay/indoc#9]
I use tabs for indentation and spaces for alignment, and would really appreciate it if indoc would also work with tab-based indentation.

**Comment by dtolnay** [comment]
That would be a nice improvement! I would accept a PR to make indoc handle tab-based indentation. Here is the relevant code that removes indentation from a string:

---

https://github.com/dtolnay/indoc/blob/56948438be16b3460636d1364a4afd9e341db4b7/unindent/src/lib.rs#L49-L78

**Comment by dtolnay** [comment]
Closing for now because I don't plan to pursue this.
